CCASA/Models/Counsellor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CCASA.Models
{
    public class Counsellor:AuditableEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Qualification { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string BloodGroup { get; set; }
        public string Messege { get; set; }
    }
}

CCASA/Controllers/CounsellorController.cs
using CCASA.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace CCASA.Controllers
{
    public class CounsellorController : Controller
    {
        Class context = new Class();
        Counsellor st = new Counsellor();
        private readonly IWebHostEnvironment Environment;

        public CounsellorController(IWebHostEnvironment
            environment)
        {

            Environment = environment;
        }
        public ViewResult Index()
        {
            return View("LoginSignUp");
        }
		public async Task<ViewResult> SignUp(string txt, string email, string pswd)
		{ 
			bool isAdded = await AddNewCounsellor(txt, email, pswd);
			if (isAdded == true)
			{
				HttpContext.Response.Cookies.Append("email", email);
				HttpContext.Response.Cookies.Append("password", pswd); 
				return View("CounsellorDetails");
			}
			else
			{ 
				ViewData["Message"] = "Unable to add counsellor";
				return View("Index");
			}
		}
		[HttpPost]
		public async Task<bool> AddNewCounsellor(string txt, string email, string pswd)
		{ 
			st.Name = txt;
			st.Email = email;
			st.Password = pswd;
			CounsellorRepository counsellorRepository = new CounsellorRepository(context);
			bool isadded = await counsellorRepository.Add(st);
			return isadded;
		}

		public ViewResult CounsellorHome()
        {
            return View("CounsellorHome");
        }
        public IActionResult Remove()
        {
            HttpContext.Response.Cookies.Delete("email");
            HttpContext.Response.Cookies.Delete("password");
            return RedirectToAction("Index","Home");
        }
        public ViewResult Settings()
        {
            CounsellorRepository counsellorRepository = new CounsellorRepository(context);
            st.Email = HttpContext.Request.Cookies["email"];
            st.Name = counsellorRepository.GetCounsellorName(st.Email);
            return View("CounselorSettings", st);
        }
        public ViewResult DashBoard()
        {
            return View("CounsellorDashboard");
        }
        public async Task<ViewResult> addDetails(string religion, string blood, string qual,string gender)
        {
            st.Email= HttpContext.Request.Cookies["email"];
            st.Password= HttpContext.Request.Cookies["password"];
            st.Religion = religion;
            st.BloodGroup = blood;
            st.Qualification = qual;
            CounsellorRepository counsellorRepository = new CounsellorRepository(context);
            bool isadded = await counsellorRepository.AddDetails(st.Email,st.Password,st);
            if (isadded)
            {
                return View("CounsellorHome");
            }
            else
                return View("DetailsNotadded");
        }
        public ViewResult Upload()
        {
            return View("CounsellorUpload");
        }

        public async Task<ViewResult> updateDetails(string religion, string blood, string password, string gender,string name)
        {
            st.Email = HttpContext.Request.Cookies["email"]; 
            st.Religion = religion;
            st.BloodGroup = blood;
            st.Name = name;
            st.Password = password;
            st.Gender = gender;
            CounsellorRepository counsellorRepository = new CounsellorRepository(context);
            bool isadded = await counsellorRepository.UpdateDetails(st.Email,st);
            if (isadded)
            {
                return View("CounsellorHome");
            }
            else
                return View("DetailsNotadded");
        }
        [HttpPost]
        public IActionResult UploadFile(List<IFormFile> postedFiles)
        {
            string wwwPath = this.Environment.WebRootPath;
            string path = Path.Combine(wwwPath, "Documents");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            foreach (var file in postedFiles)
            {
                var fileName = Path.GetFileName(file.FileName);
                var pathWithFileName = Path.Combine(path, fileName);
                using (FileStream stream = new
                    FileStream(pathWithFileName,
                    FileMode.Create))
                {
                    file.CopyTo(stream);
                    ViewBag.Message = "file uploaded successfully";
                }
            }
            return View("done");
        }
    }
}

CCASA/Views/Counsellor/CounsellorDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Counselor DashBoard</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>
    <link rel="stylesheet" href="~/css/StudentDashboard.css">
</head>
<body>

    <header class="ScriptHeader">
        <div class="rt-container">
            <div class="col-rt-12">
                <div class="rt-heading">
                    <h1>Counselor Profile Page </h1>
                    <p></p>
                </div>
            </div>
        </div>
    </header>

    <section>
        <div class="rt-container">
            <div class="col-rt-12">
                <div class="Scriptcontent">

                    <!-- Student Profile -->
                    <div class="student-profile py-4">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="card shadow-sm">
                                        <div class="card-header bg-transparent text-center">
                                            @*<img class="profile_img" src="https://source.unsplash.com/250x300/?student" alt="student dp">*@
                                            <h3>Ishmam Ahasan Samin</h3>
                                        </div>
                                        <div class="card-body">
                                            <p class="mb-0"><strong class="pr-1">CounselorID:</strong>32100</p>
                                            <p class="mb-0"><strong class="pr-1">Class:</strong>4</p>
                                            <p class="mb-0"><strong class="pr-1">Section:</strong>A</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-8">
                                    <div class="card shadow-sm">
                                        <div class="card-header bg-transparent border-0">
                                            <h3 class="mb-0"><i class="far fa-clone pr-1"></i>General Information</h3>
                                        </div>
                                        <div class="card-body pt-0">
                                            <table class="table table-bordered">
                                                <tr>
                                                    <th width="30%">Qualification</th>
                                                    <td width="2%">:</td>
                                                    <td>125</td>
                                                </tr>
                                                <tr>
                                                    <th width="30%">Experience	</th>
                                                    <td width="2%">:</td>
                                                    <td>2020</td>
                                                </tr>
                                                <tr>
                                                    <th width="30%">Gender</th>
                                                    <td width="2%">:</td>
                                                    <td>Male</td>
                                                </tr>
                                                <tr>
                                                    <th width="30%">Religion</th>
                                                    <td width="2%">:</td>
                                                    <td>Muslim</td>
                                                </tr>
                                                <tr>
                                                    <th width="30%">blood</th>
                                                    <td width="2%">:</td>
                                                    <td>B+</td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                    <div style="height: 26px"></div>
                                    <div class="card shadow-sm">
                                        <div class="card-header bg-transparent border-0">
                                            <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Other Information</h3>
                                        </div>
                                        <div class="card-body pt-0">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

CCASA/Views/Counsellor/CounsellorDetails.cshtml
<head>
    <title>Personal Information Form</title>
    <link rel="stylesheet" type="text/css" href="~/css/details.css">
</head>
<body>
    <h2>Personal Information Form</h2>
    <form action="/Counsellor/addDetails" method="post">
        <div>
            <label for="religion">Religion:</label>
            <select id="religion" name="religion">
                <option value="">Select Religion</option>
                <option value="Hinduism">Hinduism</option>
                <option value="Islam">Islam</option>
                <option value="Christianity">Christianity</option>
                <option value="Buddhism">Buddhism</option>
                <option value="Others">Others</option>
            </select>
        </div>
        <div>
            <label for="gender">Gender:</label>
            <select id="gender" name="gender">
                <option value="">Select Gender</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option> 
                <option value="Others">Others</option>
            </select>
        </div>

        <div>
            <label for="bloodGroup">Blood Group:</label>
            <select id="bloodGroup" name="blood">
                <option value="">Select Blood Group</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
            </select>
        </div> 

        <input type="submit" value="Submit">
    </form>
</body>

CCASA/Views/Counsellor/CounsellorHome.cshtml
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CCASA</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/StudentHome.css">

</head>

<body>
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container ">
            <a class="navbar-brand " href="#">Career Counselling and Self assesment </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0"> 
                    <li class="nav-item">
                        <input type="submit" value="Upload" class="btn btn-primary nav-link" style="background-color: rgb(23, 23, 54);" onclick="location.href='@Url.Action("Upload", "Counsellor")'" />
                    </li>
                    <li class="nav-item">
                        <input type="submit" value="DashBoard" class="btn btn-primary nav-link" style="background-color: rgb(23, 23, 54);" onclick="location.href='@Url.Action("DashBoard", "Counsellor")'" />
                    </li>
                    <li class="nav-item">
                        <input type="submit" value="Progress" class="btn btn-primary nav-link" style="background-color: rgb(23, 23, 54);" onclick="location.href='@Url.Action("Progress", "Counsellor")'" />
                    </li> 
                    <li>
                        <a><img class="setting" src="~/lib/settings.png" onclick="location.href='@Url.Action("Settings", "Counsellor")'" alt=""></a>
                    </li> 
                    <li class="nav-item">
                        <input type="submit" value="logout" class="btn btn-primary nav-link" style="background-color: rgb(23, 23, 54);" onclick="location.href='@Url.Action("Remove", "Counsellor")'" />
                    </li> 
                </ul>
            </div>
        </div>
    </nav>
    <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="10000">
                <img src="~/lib/image1.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>YOUR DREAM COUNSELLING HERE</h5>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, dolor alias molestias nostrum
                        eaque
                        cupiditate?
                    </p>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
                <img src="~/lib/image2.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>COMPETITIVE QUIZZES</h5>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, dolor alias molestias nostrum
                        eaque
                        cupiditate?
                    </p>

                </div>
            </div>
            <div class="carousel-item">
                <img src="~/lib/image3.jpg" class="img-dish d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>GREAT PERFECTION</h5>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, dolor alias molestias nostrum
                        eaque
                        cupiditate?
                    </p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"
            integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {

            $('.owl-carousel').owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 2
                    },
                    1000: {
                        items: 3
                    }
                }
            })
        });
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
            integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="../static/addToCart.js"></script>

</body>


</html>

CCASA/Views/Counsellor/CounsellorUpload.cshtml
<form method="post" enctype="multipart/form-data"
      asp-action="UploadFile" asp-controller="Counsellor">
    <span>Select File: </span>
    <input type="file" name="postedFiles" multiple />
    <input type="submit" value="Submit">
</form>

CCASA/Views/Counsellor/CounselorSettings.cshtml
@using CCASA.Models
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Update Profile</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/settings.css">

</head>

<body>
    <div class="container">
        <div class="row gutters">
            <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="account-settings">
                            <div class="user-profile">
                                <div class="user-avatar">
                                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Maxwell Admin">
                                </div>
                                <h5 class="user-name">@Model.Name</h5>
                                <h6 class="user-email">@Model.Email</h6>
                            </div>
                            <div class="about">
                                <h5 class="mb-2 text-primary">About</h5>
                                <p></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <h6 class="mb-3 text-primary">Personal Details</h6>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="fullName">Full Name</label>
                                    <input type="text" class="form-control" id="fullName" name="name" placeholder="Enter full name">
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="religon">Religon</label>
                                    <input type="text" class="form-control" id="religion" name="religion" placeholder="Enter Religion">
                                </div>
                            </div> 
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter new Password">
                                </div>
                            </div> 
                        </div>
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                @*<h6 class="mb-3 text-primary">Address</h6>*@
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="Gender">Gender</label>
                                    <input type="text" class="form-control" id="Street" name="gender" placeholder="Enter Gender">
                                </div>
                            </div>
                            
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group">
                                    <label for="bloodGroup">Blood Group</label>
                                    <input type="text" class="form-control" id="bloodGroup" name="blood" placeholder="Enter Blood Group">
                                </div>
                            </div>
                        </div>
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="text-right">
                                    <button type="button" id="submit" name="submit" class="btn btn-secondary" onclick="location.href='@Url.Action("CounsellorHome", "Counsellor")'">Cancel</button>
                                    <button type="button" id="submit" name="submit" class="btn btn-primary" onclick="location.href='@Url.Action("updateDetails", "Counsellor")'">Update</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

CCASA/Views/Counsellor/DetailsNotadded.cshtml
<head>
    <title> </title>
</head>
<body>
     <h1>Details Not Added</h1>
</body>

CCASA/Views/Counsellor/LoginSignUp.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>CCASA Counsellor</title>
	<link rel="stylesheet" type="text/css" href="~/css/LoginSignUp.css">
	<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<div class="main">
		<input type="checkbox" id="chk" aria-hidden="true"> 
		<div class="signup">
			<form action="/Counsellor/SignUp" method="post">
				<label for="chk" aria-hidden="true">Sign up</label>
				<input type="text" name="txt" placeholder="User name" required="">
				<input type="email" name="email" placeholder="Email" required="">
				<input type="password" name="pswd" placeholder="Password" required="">
				<div class="center-div">
					<input type="submit" value="Submit">
				</div>
			</form>
		</div>

		<div class="login">
			<form action="/Home/Login" method="post">
				<label for="chk" aria-hidden="true">Login</label>
				<input type="email" name="email" placeholder="Email" required="">
				<input type="password" name="password" placeholder="Password" required="">
				
				<div class="center-div">
					<input type="submit" value="Submit">
				</div>
			</form>
		</div>
	</div>
</body>
</html>

CCASA/Views/Counsellor/done.cshtml
<h1>Done</h1>